#!/usr/bin/env node
/* Pulls your runs since the plan started from Strava into js/results.js, which the site and calendar read.
   Usage: node --env-file=.env scripts/sync-strava.mjs
   Needs STRAVA_CLIENT_ID, STRAVA_CLIENT_SECRET and STRAVA_REFRESH_TOKEN (see scripts/strava-auth.mjs).
   Only new or changed activities are fetched in full, so it's cheap to run often. */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const OUT = fileURLToPath(new URL("../js/results.js", import.meta.url));
const PLAN_START = "2026-09-28";
const RUN_TYPES = ["Run", "TrailRun", "VirtualRun"];

function fail(msg) { console.error(msg); process.exit(1); }
const { STRAVA_CLIENT_ID: id, STRAVA_CLIENT_SECRET: secret, STRAVA_REFRESH_TOKEN: refresh } = process.env;
if (!id || !secret || !refresh) fail("Set STRAVA_CLIENT_ID, STRAVA_CLIENT_SECRET and STRAVA_REFRESH_TOKEN. Run scripts/strava-auth.mjs once to get the token.");

const tok = await fetch("https://www.strava.com/oauth/token", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ client_id: id, client_secret: secret, grant_type: "refresh_token", refresh_token: refresh })
});
if (!tok.ok) fail("Strava token refresh failed (" + tok.status + "): " + (await tok.text()) + "\nThe refresh token may have changed or been revoked. Run scripts/strava-auth.mjs again and update the secret.");
const auth = await tok.json();
if (auth.refresh_token && auth.refresh_token !== refresh) {
  /* Never print the token: Actions logs on a public repo are public. */
  console.log("::warning::Strava issued a new refresh token. If the next sync fails, run scripts/strava-auth.mjs again and update the STRAVA_REFRESH_TOKEN secret.");
}

async function api(path) {
  const res = await fetch("https://www.strava.com/api/v3" + path, { headers: { Authorization: "Bearer " + auth.access_token } });
  if (!res.ok) fail("Strava " + path + " returned " + res.status + ": " + (await res.text()));
  return res.json();
}

/* Keep what's already synced so unchanged activities aren't fetched again. */
const ctx = { window: {} };
try { new Function("window", readFileSync(OUT, "utf8"))(ctx.window); } catch { ctx.window.RESULTS = { runs: [] }; }
const known = new Map((ctx.window.RESULTS.runs || []).map((r) => [r.id, r]));

/* The plan runs in NZ daylight time (UTC+13), so start from midnight NZ on the first day. */
const after = Math.floor(new Date(PLAN_START + "T00:00:00+13:00").getTime() / 1000);
const list = (await api("/athlete/activities?per_page=100&after=" + after)).filter((a) => RUN_TYPES.includes(a.sport_type || a.type));

const runs = [];
let fetched = 0;
for (const a of list) {
  const id = String(a.id), old = known.get(id);
  /* Entries without laps are from an older version of this script, so fetch those again. */
  if (old && old.laps && old.m === Math.round(a.distance * 10) / 10 && old.sec === a.moving_time && old.name === a.name) { runs.push(old); continue; }
  const d = await api("/activities/" + id);
  fetched++;
  runs.push({
    id,
    date: d.start_date_local.slice(0, 10),
    start: d.start_date_local.slice(0, 19),
    name: d.name,
    m: Math.round(d.distance * 10) / 10,
    sec: d.moving_time,
    hr: d.average_heartrate ? Math.round(d.average_heartrate) : null,
    maxHr: d.max_heartrate || null,
    elev: Math.round(d.total_elevation_gain || 0),
    kcal: d.calories ? Math.round(d.calories) : null,
    /* Per-km splits as [metres, moving seconds, avg HR]. */
    splits: (d.splits_metric || []).map((s) => [Math.round(s.distance * 10) / 10, s.moving_time, s.average_heartrate ? Math.round(s.average_heartrate) : null]),
    /* Watch laps (auto km laps, or each rep on interval days) as [metres, moving seconds, avg HR, cadence].
       Strava gives run cadence for one foot, so double it for steps per minute. */
    laps: (d.laps || []).map((l) => [Math.round(l.distance * 10) / 10, l.moving_time, l.average_heartrate ? Math.round(l.average_heartrate) : null, l.average_cadence ? Math.round(l.average_cadence * 10) / 10 : null])
  });
}
runs.sort((a, b) => a.start.localeCompare(b.start));

const body = "/* Generated by scripts/sync-strava.mjs from Strava. Don't edit by hand. */\n" +
  "window.RESULTS = { runs: [\n" + runs.map((r) => "  " + JSON.stringify(r)).join(",\n") + "\n] };\n";
let prev = "";
try { prev = readFileSync(OUT, "utf8"); } catch {}
if (body !== prev) writeFileSync(OUT, body);
console.log(runs.length + " runs since " + PLAN_START + " (" + fetched + " fetched from Strava). " + (body !== prev ? "Updated js/results.js." : "No changes."));
